<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <NoWarn>CA1416</NoWarn>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Platforms>AnyCPU</Platforms>
    <AlgoType>Strategy</AlgoType>
    <AssemblyName>FVP_IB_Strategy</AssemblyName>
    <RootNamespace>FVP_IB_Strategy</RootNamespace>
    <StartAction>Program</StartAction>
    <StartProgram>C:\Quantower\TradingPlatform\v1.145.17\Console.StarterNew.exe</StartProgram>
    <StartArguments>--address 127.0.0.1 --port 55189</StartArguments>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>C:\Quantower\Settings\Scripts\Strategies\FVP_IB_Strategy</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>C:\Quantower\Settings\Scripts\Strategies\FVP_IB_Strategy</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="TradingPlatform.BusinessLayer">
      <HintPath>C:\Quantower\TradingPlatform\v1.146.14\bin\TradingPlatform.BusinessLayer.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(TargetDir)$(TargetFileName)" DestinationFiles="C:\Quantower\Settings\Scripts\Indicators\FVP_IB_Strategy\FVP_IB_Indicator.dll" />
  </Target>
</Project>